### ISSUE TITLE
[GenerateReleaseNotes]The term 'Get-ServiceEndPoint' is not recognized

### ISSUE THREAD

**Issue by yiminghan** [rfennell/vNextBuild#37]
I got the following when trying to generate release notes when I am in Release mode.  However this issue did not come up when I am in build mode. 

> [error]System.Management.Automation.CommandNotFoundException: The term 'Get-ServiceEndPoint' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>  
> 2016-08-22T14:41:18.8421281Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>  
>

**Comment by rfennell** [comment]
Are you running against VSTS or on-prem?
There is already an issue #24 noting I am using a preview API for the RM logic, might be that this API is not available or changed with a newer VSTS release

**Comment by yiminghan** [comment]
Hi, thanks for the reply. 
I'm running against VSTS and the app is purely base on cloud, so my guess is that it should be the newest version.

**Comment by yiminghan** [comment]
Update:  Microsoft updated their hosted agent and the issue is fixed.

**Comment by rfennell** [comment]
Greate news

**Comment by bootrider** [comment]
Still happening, Using TFS 2017, Current agent version: '2.112.0'

Runing the powershell script GenerateReleaseNotes.ps1:

```
GenerateReleaseNotes.ps1'
2017-08-17T16:55:11.1643269Z .
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-BuildWorkItems'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-BuildChangeSets'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-Detail'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-Build'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-Release'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-BuildReleaseArtifacts'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Add-Space'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Invoke-GetCommand'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Render'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-Template'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-Mode'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Add-StackItem'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Invoke-Template'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-BuildDataSet'.
2017-08-17T16:55:11.3049483Z VERBOSE: Exporting function 'Get-ReleaseByDefinitionId'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Add-Space'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Add-StackItem'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-Build'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-BuildChangeSets'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-BuildDataSet'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-BuildReleaseArtifacts'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-BuildWorkItems'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-Detail'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-Mode'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-Release'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-ReleaseByDefinitionId'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Get-Template'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Invoke-GetCommand'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Invoke-Template'.
2017-08-17T16:55:11.3205693Z VERBOSE: Importing function 'Render'.
2017-08-17T16:55:11.3205693Z VERBOSE: collectionUrl = [https://tfs/tfs/MyCollection/]
2017-08-17T16:55:11.3205693Z VERBOSE: teamproject = [MyProject]
2017-08-17T16:55:11.3205693Z VERBOSE: releaseid = [960]
2017-08-17T16:55:11.3205693Z VERBOSE: releasedefid = [5]
2017-08-17T16:55:11.3205693Z VERBOSE: stageName = [Stakeholders]
2017-08-17T16:55:11.3361916Z VERBOSE: overrideStageName = []
2017-08-17T16:55:11.3361916Z VERBOSE: buildid = [40562]
2017-08-17T16:55:11.3361916Z VERBOSE: defname = [Main.MyProgram.Deploy]
2017-08-17T16:55:11.3361916Z VERBOSE: buildnumber = [Main.MyProgram.Deploy_20170817.40562]
2017-08-17T16:55:11.3361916Z VERBOSE: outputVariableName = []
2017-08-17T16:55:11.3361916Z VERBOSE: In Release mode
2017-08-17T16:55:11.3518207Z VERBOSE: Processing all releases back to the last successful release in stage [Stakeholders]
2017-08-17T16:55:11.3518207Z VERBOSE: Getting details of release by definition [5] from server 
2017-08-17T16:55:11.3518207Z [https://tfs/tfs/MyCollection//MyProject]
2017-08-17T16:55:11.3986956Z VERBOSE: Using SystemVssConnection personal access token
2017-08-17T16:55:13.6331176Z ##[error]Get-ServiceEndPoint : The term 'Get-ServiceEndPoint' is not recognized as the name of a cmdlet, function, script file, 
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At \\Bog0009\MyProject\Main\DropLocation\Deploy\Main.MyProgram.Deploy\Main.MyProgram.Deploy_20170817.40562\ReleaseScripts\Generat
eReleaseNotes.psm1:169 char:24
+         $vssEndPoint = Get-ServiceEndPoint -Name "SystemVssConnection ...
+                        ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ServiceEndPoint:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by bootrider** [comment]
Upgrade the version of the Agent to 2.120.1...still happens
